# Generated by Django 4.2 on 2023-08-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sorular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=20, verbose_name="Kullanıcı Adı"),
                ),
                ("soru", models.TextField()),
                ("isAnonim", models.BooleanField(default=False)),
            ],
        ),
    ]
