# Generated by Django 4.2 on 2023-08-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorular", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategoriler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Kategori Adı:"
                    ),
                ),
            ],
        ),
    ]
