# Generated by Django 4.2 on 2023-08-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorular", "0002_kategoriler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kategoriler",
            name="kategori",
            field=models.CharField(max_length=30, verbose_name="Kategori Adı:"),
        ),
    ]
