# Generated by Django 4.2 on 2023-08-29 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sorular", "0003_alter_kategoriler_kategori"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cevaplar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cevap", models.TextField()),
                (
                    "sorular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sorular.sorular",
                    ),
                ),
            ],
        ),
    ]
