# Generated by Django 4.2 on 2023-08-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorular", "0005_sorular_kullanici"),
    ]

    operations = [
        migrations.AddField(
            model_name="cevaplar",
            name="username",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Admin kullanıcı"
            ),
        ),
    ]
