# Generated by Django 4.2 on 2023-09-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sorular", "0006_cevaplar_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="sorular",
            name="categories",
            field=models.ManyToManyField(to="sorular.kategoriler"),
        ),
        migrations.AddField(
            model_name="sorular",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="Sorular",
                to="sorular.kategoriler",
            ),
        ),
    ]
