# Generated by Django 4.2 on 2023-08-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_profile_email_profile_konum_profile_nickname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100, null=True)),
                ("nickname", models.CharField(max_length=100, null=True)),
                ("resim", models.ImageField(upload_to="profil_resimler/")),
            ],
        ),
    ]
