# Generated by Django 4.2 on 2023-08-11 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0006_profile_profilsahip"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="konum",),
        migrations.RemoveField(model_name="profile", name="profilSahip",),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanici",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.CharField(max_length=100, verbose_name="Kullanıcı email"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="isim",
            field=models.CharField(max_length=100, verbose_name="Kullanıcı İsmi"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(max_length=100, verbose_name="Kullanıcı nickname"),
        ),
        migrations.DeleteModel(name="Prof",),
    ]
