# Generated by Django 4.2 on 2023-08-22 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0007_remove_profile_konum_remove_profile_profilsahip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Kullanıcı email"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="isim",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Kullanıcı İsmi"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Kullanıcı nickname"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="resim",
            field=models.ImageField(null=True, upload_to="profil_resimler/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanici",
            ),
        ),
    ]
