# Generated by Django 4.2 on 2023-08-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_profile_email_alter_profile_isim_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="user", new_name="owner",
        ),
    ]
